eureka:
   client:
      healthcheck:
         enabled: false
         
management:
   endpoints:
      web:
         exposure:
            include: "*"
      health:
         show-details: always
      hystrix:
         stream:
            enabled: true

hystrix:
   dashboard:
      proxy-stream-allow-list: "*"
spring:
   data:
      mongodb:
         field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
         uri: mongodb+srv://minh160302:Canhminh-160302@cluster0.6ffh6.mongodb.net/myFirstDatabase?retryWrites=true&w=majority




